### ISSUE TITLE
Tutorial homepage still drawn/visible (under) any tutorial you start 

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-tutorial#7]
When you begin a tutorial, if you scroll down in your browser (Mozilla, firefox v46) the home page is still visible (with the top portion from the initial browser window frame showing the tutorial).  In fact the very first tutorial you must scroll down to read the instructions (i.e., the assignment) and the home page appears below the text and is very confusing. Is there a way to "clear" the home page as it seems the tutorial pages/ui is being superimposed on top of the home page? 

Screenshot attached...

<img width="1263" alt="screen shot 2016-08-09 at 11 21 56 am" src="https://cloud.githubusercontent.com/assets/7816715/17524293/9f57b5bc-5e23-11e6-83f2-70ebdb1ec252.png">

Note, I was running this locally on localhost:8080 on OSX as well

**Comment by lzbj** [comment]
@mrutkows , agree with you, probably start from a new tab is an option.
